theme: jekyll-theme-cayman
title: Dark Risings (v2.0)
description: A fun and progressive redux designed by and for the players at large

defaults:
    post_pages:
        scope:
          path: "posts"
          type: "pages"
        values:
          layout: "default"
          comments: true
    regular_pages:
        scope:
          path: "pages"
          type: "pages"
        values:
          layout: "default"
          comments: false
      pipeline_pages:
        scope:
          path: "pipelines"
          type: "pages"
        values:
          layout: "default"
          comments: true
