theme: jekyll-theme-cayman
title: Dark Risings (v2.0)
description: A fun and progressive redux designed by and for the players at large

defaults:
    post_pages:
        scope:
          path: "/posts/"
        values:
          layout: default
          comments: true
    regular_pages:
        scope:
          path: pages
        values:
          layout: "default"
